server:
  port: 8080

spring:
  application:
    name: iot-service
  cloud:
    config:
      discovery:
        enabled: true
  datasource:
    url: jdbc:mysql://b5b7819d9b19a5:47532b88@us-cdbr-iron-east-02.cleardb.net/heroku_0abf4b67ee6747a?reconnect=true
    username: b5b7819d9b19a5
    password: "47532b88"
#    password: "123456"
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml


line.bot:
    channel-token: dRaF1mGY8pDpxRStCA7sKp+HP4CcI/t7tTH0N8S98mz1r3b7SJN3UmJHG77hsaiWMe+MTCebi3Df355ZBTPpFAliAlJN2R6hhviDlpWAmvzeLn+9VMsjkzv0su8WHUf1wMz/Aeana12Xy2binCTVzAdB04t89/1O/w1cDnyilFU=
    channel-secret: 403ebe9f219199f80cc4170d3a2290b4
    handler.path: /callback
