server:
  port: 8080

spring:
  application:
    name: iot-service
  cloud:
    config:
      discovery:
        enabled: true
  datasource:
      url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
      username: root
#      password: "root"
      password: "123456"
      driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
